server:
  port: 14100
spring:
  application:
    name: sardine-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: sardine-server1
          predicates:
            - Path=/server1/**
          uri: http://127.0.0.1:14101
          filters:
            - StripPrefix=1
        - id: sardine-server2
          predicates:
            - Path=/server2/**
          uri: http://127.0.0.1:14102
          filters:
            - StripPrefix=1
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 3000
sardine:
  limit-rules:
    - url: /server1/hello
      rate-type: overall
      token-count: 1
      interval: 1000
    - url: /server2/hello
      rate-type: overall
      token-count: 1
      interval: 1000