server:
  port: 12580
spring:
  application:
    name: sardine-rocketmq
rocketMq:
  name-server: 127.0.0.1:9876
  producer:
    group: ${spring.application.name}       # 发送同一类消息设置为同一个Group，保证唯一
    send-message-timeout: 10000             # 发送消息的超时时间，默认3000
    retry-times-when-send-failed: 2         # 发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 2   # 发送异步消息失败重试次数，默认2
    max-message-size: 4096                  # 消息的最大长度，默认 1024*1024*4 = 4M
    compress-message-body-threshold: 4096   # 压缩消息阈值，默认4K
    retry-next-server: false                # 是否在内部发送失败时重试另一个Broker，默认false

